---
include:
  - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/salsa-ci.yml
  - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/pipeline-jobs.yml

stages:
  - build
  - publish
  - test
  - deploy

pages:
  image: registry.salsa.debian.org/salsa-ci-team/ci-image-git-buildpackage:latest
  stage: deploy
  artifacts:
    paths:
      - public
  only:
    - master
  script:
    - git clean -fdx
    - gitlab-ci-git-buildpackage-all
    - gitlab-ci-aptly
