---
include:
  - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/salsa-ci.yml
  - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/pipeline-jobs.yml

pages:
  image: registry.salsa.debian.org/salsa-ci-team/ci-image-git-buildpackage:latest
  stage: publish
  artifacts:
    paths:
      - public
  only:
    - master
  script:
    - gitlab-ci-git-buildpackage-all
    - gitlab-ci-aptly
